import './globals.css'
import type { Metadata } from 'next'
import { Inter,Archivo_Black,Space_Grotesk, Nunito } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Nav from './Components/Nav'
import { Footer } from './Components/Footer'
export const metadata: Metadata = {
  title: 'Image Generator',
  description: 'Generated by create next app',
}

const header_h1 = Archivo_Black({
  subsets: ["latin"],
  weight:"400",
  variable: "--archivo"
});

const para = Inter({
  subsets: ["latin"],
  weight:"400",
  variable: "--inter"
});

const space = Space_Grotesk({
  subsets: ["latin"],
  weight:"400",
  variable: "--space"
});

const nuni = Nunito({
  subsets: ["latin"],
  weight:"800",
  variable: "--nuni"
});



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="night" className='border-[1px' lang="en">
      <body className={`${header_h1.variable} ${para.variable} ${space.variable} ${nuni.variable} overflow-x-hidden overflow-y-auto `}>
        <Nav></Nav>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
